import { Button } from "@/components/ui/button";
import { Download } from "lucide-react";
import { AnalysisResult } from "@/pages/Index";
import jsPDF from "jspdf";

interface PDFDownloadProps {
  results: AnalysisResult;
}

export const PDFDownload = ({ results }: PDFDownloadProps) => {
  const downloadPDF = () => {
    const doc = new jsPDF();
    const pageHeight = doc.internal.pageSize.height;
    const currentDate = new Date().toLocaleDateString('en-US', { 
      year: 'numeric', 
      month: 'long', 
      day: 'numeric' 
    });
    
    // Helper function to add footer
    const addFooter = () => {
      doc.setFontSize(8);
      doc.setTextColor(128, 128, 128);
      doc.text(
        "Generated by Smart Resume Analyzer | Powered by AI",
        doc.internal.pageSize.width / 2,
        pageHeight - 10,
        { align: 'center' }
      );
      doc.text(
        `Report Date: ${currentDate}`,
        doc.internal.pageSize.width / 2,
        pageHeight - 5,
        { align: 'center' }
      );
      doc.setTextColor(0, 0, 0); // Reset to black
    };
    
    doc.setFontSize(20);
    doc.text("Resume Analysis Report", 20, 20);
    
    doc.setFontSize(14);
    doc.text(`Job Fit Score: ${results.jobFitScore}%`, 20, 40);
    
    doc.setFontSize(12);
    doc.text("Matched Skills:", 20, 55);
    results.matchedSkills.forEach((skill, idx) => {
      doc.text(`- ${skill}`, 25, 65 + idx * 7);
    });
    
    const missingY = 65 + results.matchedSkills.length * 7 + 10;
    doc.text("Missing Skills:", 20, missingY);
    results.missingSkills.forEach((skill, idx) => {
      doc.text(`- ${skill}`, 25, missingY + 10 + idx * 7);
    });
    
    const suggestionsY = missingY + 10 + results.missingSkills.length * 7 + 10;
    doc.text("Recommendations:", 20, suggestionsY);
    results.suggestions.forEach((suggestion, idx) => {
      const lines = doc.splitTextToSize(suggestion, 170);
      doc.text(lines, 25, suggestionsY + 10 + idx * 14);
    });
    
    // Add footer to all pages
    const pageCount = doc.internal.pages.length - 1;
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      addFooter();
    }
    
    doc.save("resume-analysis.pdf");
  };

  return (
    <Button onClick={downloadPDF} className="gap-2 gradient-button neon-border text-white">
      <Download className="h-4 w-4" />
      📥 Download PDF Report
    </Button>
  );
};
